experiment:
  # seed: 42  <-- REMOVED
  device: "cuda"  # or "cpu"

seeds:
  global: 42
  model: 42
  clustering: 42
  tsne: 42

data:
  root: "data/processed/graphs"
  homo: "homo.pt"
  hetero_walk: "hetero_walk.pt"
  hetero_multi: "hetero_multi.pt"

model:
  in_dim: 23  # Number of input features
  hidden_dim: 32
  out_dim: 16 # Embedding dimension (d=16)
  heads: 4
  dropout: 0.5
  lambda_struct: 1.0

training:
  lr: 0.001
  epochs: 5000
  early_stopping_patience: 50
  neg_sampling_ratio: 1.0

clustering:
  n_clusters: 8  # Need to determine appropriate K, or maybe make it a list to try
